//
//  TravelPlan.swift
//  TravelPlanner
//
//  Travel plan model generated by AI
//

import Foundation

struct TravelPlan: Codable, Identifiable {
    let id: String
    let userId: String
    let destination: String
    let startDate: Date
    let endDate: Date
    let description: String
    let activities: [Activity]
    let createdAt: Date
    
    init(id: String = UUID().uuidString,
         userId: String,
         destination: String,
         startDate: Date,
         endDate: Date,
         description: String,
         activities: [Activity] = [],
         createdAt: Date = Date()) {
        self.id = id
        self.userId = userId
        self.destination = destination
        self.startDate = startDate
        self.endDate = endDate
        self.description = description
        self.activities = activities
        self.createdAt = createdAt
    }
}

struct Activity: Codable, Identifiable {
    let id: String
    let title: String
    let description: String
    let time: Date
    let location: String
    
    init(id: String = UUID().uuidString,
         title: String,
         description: String,
         time: Date,
         location: String) {
        self.id = id
        self.title = title
        self.description = description
        self.time = time
        self.location = location
    }
}

