//
//  TravelPlan.swift
//  TravelPlanner
//
//  Travel plan model generated by AI
//

import Foundation

struct TravelPlan: Codable, Identifiable {
    let id: String
    let userId: String
    let destination: String
    let displayName: String? // Corrected/formatted destination name from AI
    let countryCode: String? // ISO 3166-1 alpha-2 country code for flag
    let startDate: Date
    let endDate: Date
    let budget: String
    let specialRequests: String?
    var days: [DayItinerary]
    let totalEstimatedCost: String?
    let highlights: [String]
    let localTips: [String]
    let createdAt: Date
    var updatedAt: Date
    
    // Computed property for flag emoji
    var flagEmoji: String? {
        guard let countryCode = countryCode, countryCode.count == 2 else { return nil }
        let base: UInt32 = 127397
        var emoji = ""
        for scalar in countryCode.uppercased().unicodeScalars {
            if let unicode = UnicodeScalar(base + scalar.value) {
                emoji.append(String(unicode))
            }
        }
        return emoji.isEmpty ? nil : emoji
    }
    
    // Display name with fallback to destination
    var formattedName: String {
        return displayName ?? destination
    }
    
    init(id: String = UUID().uuidString,
         userId: String,
         destination: String,
         displayName: String? = nil,
         countryCode: String? = nil,
         startDate: Date,
         endDate: Date,
         budget: String,
         specialRequests: String? = nil,
         days: [DayItinerary] = [],
         totalEstimatedCost: String? = nil,
         highlights: [String] = [],
         localTips: [String] = [],
         createdAt: Date = Date(),
         updatedAt: Date = Date()) {
        self.id = id
        self.userId = userId
        self.destination = destination
        self.displayName = displayName
        self.countryCode = countryCode
        self.startDate = startDate
        self.endDate = endDate
        self.budget = budget
        self.specialRequests = specialRequests
        self.days = days
        self.totalEstimatedCost = totalEstimatedCost
        self.highlights = highlights
        self.localTips = localTips
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}

// Shared helper: derive a sortable minute-of-day value from a free-form time
// string (e.g. "9:00 AM", "Lunch"). Used to assign an initial `order` to
// activities/restaurants that predate explicit ordering.
enum TimeOrdering {
    static func sortKey(for timeString: String) -> Int {
        let lower = timeString.lowercased().trimmingCharacters(in: .whitespaces)
        let isPM = lower.contains("pm")
        let isAM = lower.contains("am")
        let digits = lower.filter { $0.isNumber || $0 == ":" }
        let parts = digits.split(separator: ":")
        var hour = Int(parts.first ?? "0") ?? 0
        let minute = Int(parts.dropFirst().first ?? "0") ?? 0
        if isPM && hour < 12 { hour += 12 }
        if isAM && hour == 12 { hour = 0 }
        if !isAM && !isPM {
            if lower.contains("lunch") { hour = 13 }
            else if lower.contains("dinner") { hour = 19 }
            else if lower.contains("breakfast") { hour = 8 }
        }
        return hour * 60 + minute
    }
}

struct DayItinerary: Codable, Identifiable {
    let id: String
    let dayNumber: Int
    let date: Date
    let theme: String?
    var activities: [Activity]
    var restaurants: [Restaurant]
    let hiddenGems: [String]
    let tip: String?
    let estimatedDailyCost: String?
    
    init(id: String = UUID().uuidString,
         dayNumber: Int,
         date: Date,
         theme: String? = nil,
         activities: [Activity] = [],
         restaurants: [Restaurant] = [],
         hiddenGems: [String] = [],
         tip: String? = nil,
         estimatedDailyCost: String? = nil) {
        self.id = id
        self.dayNumber = dayNumber
        self.date = date
        self.theme = theme
        self.activities = activities
        self.restaurants = restaurants
        self.hiddenGems = hiddenGems
        self.tip = tip
        self.estimatedDailyCost = estimatedDailyCost
    }
}

struct Activity: Codable, Identifiable {
    let id: String
    var time: String
    var name: String
    var description: String
    var duration: String?
    var cost: String?
    var location: String?
    var tips: String?
    var order: Int // Explicit position within the day's merged timeline
    var swapOptions: [ActivityOption]? // AI swap pool, generated once per activity

    init(id: String = UUID().uuidString,
         time: String,
         name: String,
         description: String,
         duration: String? = nil,
         cost: String? = nil,
         location: String? = nil,
         tips: String? = nil,
         order: Int = 0,
         swapOptions: [ActivityOption]? = nil) {
        self.id = id
        self.time = time
        self.name = name
        self.description = description
        self.duration = duration
        self.cost = cost
        self.location = location
        self.tips = tips
        self.order = order
        self.swapOptions = swapOptions
    }

    /// Snapshot of this activity's descriptive fields as a swap option (for revert).
    var asOption: ActivityOption {
        ActivityOption(name: name, description: description, duration: duration, cost: cost, location: location)
    }
}

/// One candidate the user can swap an activity to. Generated once, then reused.
struct ActivityOption: Codable, Identifiable, Hashable {
    var id: String
    var name: String
    var description: String
    var duration: String?
    var cost: String?
    var location: String?

    init(id: String = UUID().uuidString,
         name: String,
         description: String,
         duration: String? = nil,
         cost: String? = nil,
         location: String? = nil) {
        self.id = id
        self.name = name
        self.description = description
        self.duration = duration
        self.cost = cost
        self.location = location
    }
}

struct Restaurant: Codable, Identifiable {
    let id: String
    var name: String
    var cuisine: String?
    var priceRange: String?
    var time: String
    var reservation: String?
    var description: String?
    var location: String?
    var order: Int // Explicit position within the day's merged timeline

    init(id: String = UUID().uuidString,
         name: String,
         cuisine: String? = nil,
         priceRange: String? = nil,
         time: String,
         reservation: String? = nil,
         description: String? = nil,
         location: String? = nil,
         order: Int = 0) {
        self.id = id
        self.name = name
        self.cuisine = cuisine
        self.priceRange = priceRange
        self.time = time
        self.reservation = reservation
        self.description = description
        self.location = location
        self.order = order
    }
}

